name: Final_CI_Pipeline

on:
  push:
    branches:
      - '**'
env:
  REGISTRY: "teebra2.jfrog.io"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: |
          mvn clean install
      
      - name: check
        run: |
          ls
          cd target
          ls
          cd ..
      
      - name: Zip
        run: |
          zip -r jar_archive.zip target
      
      - name: Archive Maven Package
        uses: actions/upload-artifact@v3
        with:
          name: jar_package
          path: |
            jar_archive.zip
          retention-days: 30
  
  upload_artifact:
    name: Upload LYNX Artifact
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to Jfrog
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://${{ env.REGISTRY }}
          JF_USER: ${{ secrets.JFROG_USERNAME }}
          JF_PASSWORD: ${{ secrets.JFROG_API_KEY }}
      
      - name: Upload Artifact to Artifactory
        run: |