name: Get Tags

on:
  push:
    branches:
      - main

jobs:
  get-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Current Tag
      run: |
        currentTag=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)
        echo "Current tag: $currentTag"
        echo "::set-output name=currentTag::$currentTag"

    - name: Get Previous Tag
      id: get-previous-tag
      run: |
        currentTag=${{ steps.get-current-tag.outputs.currentTag }}
        previousTag=$(git describe --tags --abbrev=0 $currentTag^)
        echo "Previous tag: $previousTag"
        echo "::set-output name=previousTag::$previousTag"

    - name: Use Tags in Subsequent Steps
      run: |
        currentTag=${{ steps.get-previous-tag.outputs.currentTag }}
        previousTag=${{ steps.get-previous-tag.outputs.previousTag }}
        echo "Current tag: $currentTag"
        echo "Previous tag: $previousTag"
