name: List Tags

on:
  push:
    branches:
      - main

jobs:
  list-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Tags
      run: |
        git fetch --tags
        git tag

        echo "Get current and previous tags"

        current_tag=$(git describe --tags --abbrev=0)
        previous_tag=$(git describe --tags --abbrev=0 $current_tag^{} 2>/dev/null || echo "No previous tag")

        echo "Current tag: $current_tag"
        echo "Previous tag: $previous_tag"




    # - name: tag
    #   run: git tag
    
    # - name: get current and pervious tags
    #   run: |
    #     current_tag=$(git describe --tags --abbrev=0)
    #     previous_tag=$(git describe --tags --abbrev=0 $current_tag^)

    #     echo "Current tag: $current_tag"
    #     echo "Previous tag: $previous_tag"



