name: Extract Jira Issue Numbers

# on:
#   push:
#     branches:
#       - main

on: [workflow_dispatch]

jobs:
  extract-jira-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get the latest release tag
      id: latest_release
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "Latest release tag: $latest_tag"
        echo "::set-output name=latest_tag::$latest_tag"

      - name: Get the previous release tag
        id: previous_release
        run: |
          previous_tag=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
          echo "Previous release tag: $previous_tag"
          echo "::set-output name=previous_tag::$previous_tag"

      - name: List commits between releases
        id: list_commits
        run: |
          git log --oneline ${{ steps.previous_release.outputs.previous_tag }}..${{ steps.latest_release.outputs.latest_tag }}
          echo "::set-output name=commits::$(git log --oneline ${{ steps.previous_release.outputs.previous_tag }}..${{ steps.latest_release.outputs.latest_tag }})"

      - name: Display commits
        run: echo "Commits between releases: ${{ steps.list_commits.outputs.commits }}"

