name: Get Commits Between Releases

#on: [workflow_dispatch]
on:
  push:
    branches:
      - main

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get all tags
      id: get_tags
      run: echo "::set-output name=tags::$(git tag -l)"

    - name: Display tags
      run: |
        tags="${{ steps.get_tags.outputs.tags }}"
        echo "Available tags: $tags"