name: Get Commits Between Releases

on: [workflow_dispatch]

jobs:
  get-release-tags:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get current release tag
        id: current-release-tag
        run: |
          echo "Current release tag: $(git describe --tags | sort -V | tail -n 1)"

      - name: Get previous release tag
        id: previous-release-tag
        run: |
          echo "Previous release tag: $(git describe --abbrev=0 --tags | sort -V | tail -n 2 | head -n 1)"

      - name: Get commits between current and previous release tag
        id: commits-between-release-tags
        run: |
          echo "Commits between current and previous release tag:"
          git log $(previous-release-tag)..$(current-release-tag)

