name: Get Current and Previous Tags

on:
  push:
    branches:
      - main

jobs:
  get-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch tags
        uses: WyriHaximus/github-action-fetch-tags@v1

      - name: Get current tag
        id: current-tag
        run: echo "Current tag $(git describe --tags)"

      - name: Get previous tag
        id: previous-tag
        run: |
          previous_commit=$(git rev-list --tags --max-count=1 ^HEAD)
          previous_tag=$(git describe --tags --exact-match $previous_commit)
          echo "Previous tag: $previous_tag"

      - name: Display tags
        run: echo "Current tag ${{ steps.current-tag.outputs.tag }}"
        run: echo "Previous tag ${{ steps.previous-tag.outputs.tag }}"
