name: Get Commits Between Releases

on: [workflow_dispatch]

jobs:
  get-tags-and-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get current release tag
        id: get-current-tag
        run: echo "Current release tag: $(git tag --sort=version:refname | tail -n 1)"

      - name: Get previous release tag
        id: get-previous-tag
        run: |
          current_tag=$(git tag --sort=version:refname | tail -n 1)
          previous_tag=$(git rev-parse $current_tag^1)
          echo "Previous release tag: $previous_tag"

      - name: Get commits between current and previous release tag
        id: get-commits
        run: |
          current_tag=$(git tag --sort=version:refname | tail -n 1)
          previous_tag=$(git rev-parse $current_tag^1)
          git log $previous_tag..$current_tag

