name: Get Commits Between Releases

#on: [workflow_dispatch]
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List commits between tags
        run: |
          current_tag="Release-1.6.0.0"
          previous_tag="Release-1.5.0.0"
          
          git log --pretty=format:"%h - %an, %ar : %s" $previous_tag..$current_tag