name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_maven_package:
    name: Build Maven Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn clean install

      - name: Archive Maven Package
        uses: actions/upload-artifact@v2
        with:
          name: jar_package
          path: target/*.jar

  analyze_with_sonarqube:
    name: Analyze with SonarQube
    needs: build_maven_package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Maven Package Artifact
        uses: actions/download-artifact@v2
        with:
          name: jar_package
          path: target

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar -Dsonar.projectKey=sonartest -Dsonar.sources=. -Dsonar.tests=. 
          ls

