name: SonarQube Scan

on:
  push:
    branches:
      - '*'

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build project
        run: mvn clean install

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-url: ${{ secrets.SONAR_HOST_URL }}
          project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sources: ${{ github.workspace }}/target/*.jar  # Path to the JAR file created by the previous workflow.

      - name: Get SonarQube Scan Results
        run: |
          wget ${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }} -O sonarqube-results.json

      - name: Display SonarQube Scan Results
        run: cat sonarqube-results.json
