name: Build and Test with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Upload HTML Table to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artefact
        path: |
          target/*.jar

    - name: Scan JAR file with SonarQube
      uses: SonarSource/sonarqube-scan-action@v7
      with:
        serverUrl: ${{ secrets.SONAR_HOST_URL }}
        token: ${{ secrets.SONAR_TOKEN }}
        organization: sonartest
        projectKey: sonartest
        sonarScanner: sonar-scanner-cli-4.7.0.2747.zip
        additionalProperties: |-
          sonar.language=java
          sonar.sources=src/main/java
      
