name: SonarQube analysis

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn clean install

      # - name: Archive Maven Package
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: jar_package
      #     path: target/*.jar

      # - name: Pipeline-Scan Action Step
      #   id: pipeline-scan
      #   uses: veracode/Veracode-pipeline-scan-action@v1.0.9
      #   with:
      #     vid: ${{ secrets.VERACODE_API_ID }}
      #     vkey: ${{ secrets.VERACODE_API_KEY }}
      #     file: 'target/*.jar'
      #     project_name: ${{ env.PROJECT_NAME }}
      #     json_output: true
      #     #baseline_file: "veracode/veracode-pipeline-scan-baseline-file.json"
      #     summary_display: true
      #   continue-on-error: true

      - name: Analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectBaseDir=.
            -Dsonar.projectVersion=1.${{ github.run_number }}
            -Dsonar.sources=src/main/java
            -Dsonar.java.binaries=**classes**
            -Dsonar.exclusions=**package-info.**
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.projectKey=sonartest
            -Dsonar.projectName=sonartest 
            -Dsonar.analysis.mode=publish
            -Dsonar.dynamicAnalysis=reuseReports

  #     - name: Get branch name
  #       id: branch_name
  #       run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

  #     - name: Check branch name
  #       run: |
  #         branch_name=${{ steps.branch_name.outputs.branch_name }}
  #         if [[ $branch_name == release*0 ]]; then
  #           echo "fail"
  #         else
  #           echo "success"
  #         fi
  #         #ls src/bin/script.py

  # check:
  #   runs-on: ubuntu-latest
  #   needs: [Analysis]
  #   #if: (startsWith(github.ref, 'refs/heads/release') && endsWith(github.ref, '0')) == true
  #   steps:
  #     - name: check
  #       run: |
  #         echo test
  #         # ls src/bin/script.py
  
  # check_1:
  #   runs-on: ubuntu-latest
  #   needs: [Analysis, check]
  #   #if: (startsWith(github.ref, 'refs/heads/release') && endsWith(github.ref, '0')) == true
  #   steps:
  #     - name: check
  #       run: |
  #         echo test
  #         # ls src/bin/script.py
  
  # list-jobs:
  #   runs-on: ubuntu-latest
  #   needs: [Analysis, check, check_1]
  #   steps:
  #     - uses: ./sonarqube.yml
  #       id: list-jobs
  #     - run: cat ${{ steps.list-jobs.outputs.jobs-file }}


  # Veracode:
  #   if: (startsWith(github.ref, 'refs/heads/release') && endsWith(github.ref, '0')) == false

  #   runs-on: ubuntu-latest
  #   needs: [Analysis,check, check_1,list-jobs]

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Veracode
  #       run: |
  #         sleep 20s
  #         #ls src/bin/script.py

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: [Analysis, check, Veracode, check_1,list-jobs]
  #   #if: needs.Veracode.result != 'failure' || needs.veracode.result == 'success' || needs.veracode.result == 'skipped'
  #   if: always() && needs.Veracode.result != 'failure' && needs.check.result != 'failure' && needs.Analysis.result != 'failure' && needs.check_1.result != 'failure' && needs.check.result != 'skipped' && needs.Analysis.result != 'skipped' && needs.check_1.result != 'skipped'
  #   steps:
  #     - name: Docker Job
  #       run: |
  #         echo docker run
  #         echo 'needs.Veracode.result'

  # upload:
  #   runs-on: ubuntu-latest
  #   needs: [Analysis, check, check_1, docker, Veracode, list-jobs]
  #   #if: needs.Veracode.result != 'failure' || needs.veracode.result == 'success' || needs.veracode.result == 'skipped'
  #   if: always() && needs.Veracode.result != 'failure' && needs.docker.result != 'failure' && needs.check.result != 'failure' && needs.Analysis.result != 'failure' && needs.check_1.result != 'failure' && needs.docker.result != 'skipped' && needs.check.result != 'skipped' && needs.Analysis.result != 'skipped' && needs.check_1.result != 'skipped'
  #   steps:
  #     - name: Upload Job1
  #       if: (startsWith(github.ref, 'refs/heads/release') && endsWith(github.ref, '0')) == false
  #       run: |
  #         echo docker run
      
  #     - name: Upload Job2
  #       run: |
  #         echo docker run
      
  #     - name: Upload Job3
  #       run: |
  #         echo docker run
      
  #     - name: Upload Job4
  #       run: |
  #         echo docker run
  #         echo "${{needs.Veracode.result}}"
    
