name: TriggerWorkflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building something..."

  trigger_target_workflow:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger MyTargetWorkflow
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflow } = await github.actions.getWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 123456, // Replace with the ID of MyTargetWorkflow
            });
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id,
              ref: "main", // Replace with the branch you want to trigger MyTargetWorkflow on
            });
