name: MyTargetWorkflow

on:
  workflow_dispatch:
  
jobs:
  target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Target Job
        run: echo "This is the target job..."
