name: Veracode Workflow
on:
  # workflow_run:
  #   workflows: ["SonarQube analysis"]
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  veracode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Veracode Scan
        run: mkdir artifacts

      - name: Download build artifact from triggered workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: jar_package
          path: ./artifacts
          search_artifacts: true

      - name: Veracode Scan
        run: |
          echo veracode scan start
          cd artifacts
          ls
