name: Veracode Workflow

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  veracode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Veracode Scan
        run: |
          mkdir artifacts
          cd artifacts
          echo "test the loop" > test.txt
          cat test.txt
      
      # - name: Push changes
      #   run: |
      #     git config --global user.name "sdfsdfs"
      #     git config --global user.email "sdfsdfsf"
      #     git add "artifacts"
      #     git stash
      #     git pull origin main || echo "Couldn't find remote branch"
      #     git checkout stash -- .
      #     git commit -m "Baseline File push from pipeline"
      #     git push origin HEAD:main --force-with-lease

      - name: Set up Git
        run: |
          if ! git diff --quiet; then
            git config user.name sdfsdfsd
            git config user.email sdfsdfsdfs
            git add .
            git commit -m "updated"
          else
            echo "No changes found"
          fi

      - name: Push changes
        #if: startsWith(github.ref, 'refs/heads/release-') || github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: ${{ github.ref }}

      