name: TriggerWorkflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building something..."

# This workflow file doesn't need to include the trigger for the next workflow
