name: MyTargetWorkflow

# on: [workflow_dispatch]

# on:
#   workflow_run:
#     workflows: ["TriggerWorkflow"]
#     types:
#       - completed

on:
  repository_dispatch:
    types: [my-event]

jobs:
  set_env:
    name: Setup Global Environments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Docker Tags
        run: |
            echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
            echo "RELEASE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec 2>/dev/null)" >> $GITHUB_ENV
            echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME)" >> $GITHUB_ENV
            echo "CURRENT_DATE_TIME=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV
            echo BUILD_NUMBER="${{ github.run_number }}" >> $GITHUB_ENV
      - name: Creating Major TAGs
        id: set_env
        run: |
            echo PROJECT_NAME=${{ env.PROJECT_NAME }} >> $GITHUB_OUTPUT
            echo RELEASE_VERSION=${{ env.RELEASE_VERSION }} >> $GITHUB_OUTPUT
            echo BRANCH_NAME=${{ env.BRANCH_NAME }} >> $GITHUB_OUTPUT
            echo CURRENT_DATE_TIME=${{ env.CURRENT_DATE_TIME }} >> $GITHUB_OUTPUT
            echo BUILD_NUMBER=${{env.BUILD_NUMBER }} >> $GITHUB_OUTPUT
    outputs:
      PROJECT_NAME: ${{ steps.set_env.outputs.PROJECT_NAME }}
      RELEASE_VERSION: ${{ steps.set_env.outputs.RELEASE_VERSION }}
      BRANCH_NAME: ${{ steps.set_env.outputs.BRANCH_NAME }}
      CURRENT_DATE_TIME: ${{ steps.set_env.outputs.CURRENT_DATE_TIME }}
      BUILD_NUMBER: ${{ steps.set_env.outputs.BUILD_NUMBER }}

  target:
    runs-on: ubuntu-latest
    needs: [set_env]
    env:
      PROJECT_NAME: ${{ needs.set_env.outputs.PROJECT_NAME }}
      RELEASE_VERSION: ${{ needs.set_env.outputs.RELEASE_VERSION }}
      BRANCH_NAME: ${{ needs.set_env.outputs.BRANCH_NAME }}
      CURRENT_DATE_TIME: ${{ needs.set_env.outputs.CURRENT_DATE_TIME }}
      BUILD_NUMBER: ${{ needs.set_env.outputs.BUILD_NUMBER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Target Job
        run: echo "This is the target job..."
      - name: Upload to Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ env.PROJECT_NAME }}-${{ env.BRANCH_NAME }}-${{ env.RELEASE_VERSION }}-${{ env.CURRENT_DATE_TIME }}-${{ env.BUILD_NUMBER }}
          path: |
            ./test.txt

      
