name: Veracode Workflow
on:
  workflow_run:
    workflows: ["SonarQube analysis"]
    types:
      - completed

jobs:
  veracode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: target/ # Modify to the destination path

      - name: Veracode Scan
        run: |
          echo veracode scan start
