name: Veracode Workflow
on:
  workflow_run:
    workflows: ["SonarQube analysis"]
    types:
      - completed

jobs:
  veracode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: jar_package
          path: target/

      - name: Veracode Scan
        run: |
          echo veracode scan start
