name: Veracode Workflow

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  veracode:
    using: "composite"
    #runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Veracode Scan
        run: |
          mkdir artifacts
          cd artifacts
          echo "test the loop" > test.txt
          cat test.txt
      
      - name: push
        uses: ./actions/push-changes-without-triggering-workflow@v1
        with:
          branch: main
          pat: ${{ secrets.GITHUB_TOKEN }}

      