name: Veracode Workflow
on:
  workflow_run:
    workflows: ["SonarQube analysis"]
    types:
      - completed

jobs:
  veracode:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Veracode Scan
        run: mkdir Artifact

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: jar_package-${{ github.sha }}
          path: Artifact/

      - name: Veracode Scan
        run: |
          ls
          echo veracode scan start
