name: Veracode Workflow
on:
  workflow_run:
    workflows: ["SonarQube analysis"]
    types:
      - completed

jobs:
  veracode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: jar_package-${{ github.run_number }}
          path: target/

      - name: Veracode Scan
        run: |
          echo veracode scan start
