name: TriggerWorkflow

# on:
#   push:
#     branches:
#       - main

# on:
#   push:
#     branches:
#       - '*'
#       # - '!main'
#       # - '!release-*.0'
#   pull_request:
#     branches: 
#       - 'main'
#       - 'release-*.0'

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Executing on branch $GITHUB_REF"
  
  test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: test1.yml
          token: ${{ secrets.PAT_TOKEN }}
  
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   #if: github.event_name == 'pull_request'
  #   steps:
  #     - name: Trigger Workflow
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         event-type: my-event-${{ github.run_number }}
  #         token: ${{ secrets.PAT_TOKEN }}
  #         #repository: ${{ github.repository }}
  gg:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building something..."
  ss:
    runs-on: ubuntu-latest
    needs: [build, gg]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building something..."
  ff:
    runs-on: ubuntu-latest
    needs: [build, gg, ss]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo test

# This workflow file doesn't need to include the trigger for the next workflow
