name: TriggerWorkflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building something..."
  
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Invoke workflow without inputs
  #       uses: benc-uk/workflow-dispatch@v1
  #       with:
  #         workflow: test1.yml
  #         token: ${{ secrets.PAT_TOKEN }}
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Trigger Workflow
        if: success()
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: MyTargetWorkflow
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
  gg:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building something..."
  ss:
    runs-on: ubuntu-latest
    needs: [build, test, gg]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building something..."
  ff:
    runs-on: ubuntu-latest
    needs: [build, test, gg, ss]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo test

# This workflow file doesn't need to include the trigger for the next workflow
