name: MyTargetWorkflow

# on: [workflow_dispatch]

# on:
#   workflow_run:
#     workflows: ["TriggerWorkflow"]
#     types:
#       - completed

on:
  repository_dispatch:
    types: [my-event]

jobs:
  target:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ steps.extract-repo-name.outputs.repo-name }}
      RELEASE_VERSION: ${{ steps.version.outputs.version }}
      BRANCH_NAME: ${{ github.ref }}
      CURRENT_DATE_TIME: ${{ steps.timestamp.outputs.timestamp }}
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Extract Repository Name
        id: extract-repo-name
        run: echo "::set-output name=repo-name::$(basename -s .git ${{ github.repository }})"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Target Job
        run: echo "This is the target job..."
      - name: Upload to Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ env.PROJECT_NAME }}-${{ env.BRANCH_NAME }}-${{ env.RELEASE_VERSION }}-${{ env.CURRENT_DATE_TIME }}-${{ env.BUILD_NUMBER }}
          path: |
            ./test.txt

      - name: Set Outputs
        id: set-outputs
        run: echo "::set-output name=upload-url::${{ steps.upload-artifacts.outputs.artifact-upload-url }}"

      
